#article: https://www.bigclown.com/doc/projects/radio-co2-monitor/
#video: https://youtu.be/jGxjl5v7kqE
#images:
#  - title:
#    url: https://github.com/hardwario/website/blob/master/static/kits-images/co2-monitor/main.png
articles:
  - title: Clock with Stopwatch Activated by Accelerometer
    url: https://www.hackster.io/hubmartin/clock-with-stopwatch-activated-by-accelerometer-8b7344
    description: Nice and simple battery operated clock. Put it upside down and you can measure time to cook perfect eggs. Also displays seconds, temp, etc.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/894780/img_4140_SEJWMJXKGf.JPG?auto=compress%2Cformat&w=900&h=675&fit=min
assembly:
  - name: HARDWARIO LCD Module
  - name: HARDWARIO Core Module
  - name: HARDWARIO Battery Module